"""Shared pytest fixtures for LZ4 tests."""

from __future__ import annotations

import os
import pytest

from tests.datagen import generate_buffer


# ---------------------------------------------------------------------------
# Common test data fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def empty_data() -> bytes:
    """Empty input."""
    return b""


@pytest.fixture
def small_text() -> bytes:
    """Small textual data (< LZ4_minLength)."""
    return b"Hello World!"


@pytest.fixture
def lorem_ipsum() -> bytes:
    """Repeating Lorem Ipsum text (matches decompress-partial.c)."""
    text = (
        b"Lorem ipsum dolor sit amet, consectetur adipiscing elit, "
        b"sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. "
        b"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris "
        b"nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in "
        b"reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla "
        b"pariatur. Excepteur sint occaecat cupidatat non proident, sunt in "
        b"culpa qui officia deserunt mollit anim id est laborum. "
    )
    return text * 3  # ~1.4 KB


@pytest.fixture
def repetitive_data() -> bytes:
    """Highly repetitive data (excellent compression)."""
    return b"AAAA" * 1000


@pytest.fixture
def all_zeros() -> bytes:
    """All-zero data."""
    return b"\x00" * 10000


@pytest.fixture
def pattern_data() -> bytes:
    """Repeating byte pattern 0..255."""
    return bytes(range(256)) * 100


@pytest.fixture
def random_data() -> bytes:
    """Pseudo-random (incompressible) data."""
    return os.urandom(10000)


@pytest.fixture
def one_byte() -> bytes:
    """Single byte input."""
    return b"A"


@pytest.fixture
def compressible_data() -> bytes:
    """Compressible data generated by datagen (50% match probability)."""
    return generate_buffer(100_000, match_proba=0.5, seed=42)


@pytest.fixture
def incompressible_data() -> bytes:
    """Incompressible data generated by datagen (0% match probability)."""
    return generate_buffer(10_000, match_proba=0.0, seed=42)


@pytest.fixture
def highly_compressible_data() -> bytes:
    """Highly compressible data (90% match probability)."""
    return generate_buffer(100_000, match_proba=0.9, seed=42)


@pytest.fixture
def large_data() -> bytes:
    """Large data block (1 MB)."""
    return generate_buffer(1_000_000, match_proba=0.5, seed=123)
