"""
Comprehensive tests for the LZ4 block compression/decompression module.

Tests cover:
- compress/decompress round-trip with various data patterns
- compress_bound validation
- Partial decompression (ported from decompress-partial.c)
- Dictionary-based decompression (ported from decompress-partial-usingDict.c)
- Streaming encode/decode
- Edge cases (1 byte, empty, all zeros, max input validation)
- Error handling (corrupted data, truncated data, oversized input)
- Data generated by datagen with different compressibility patterns
"""

from __future__ import annotations

import os
import struct
import pytest

import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from lz4 import LZ4CompressError, LZ4DecompressError
from lz4.block import (
    compress,
    decompress,
    compress_bound,
    compress_dest_size,
    decompress_partial,
    decompress_using_dict,
    decompress_partial_using_dict,
    LZ4StreamEncode,
    LZ4StreamDecode,
    LZ4_MAX_INPUT_SIZE,
    MINMATCH,
    LASTLITERALS,
)
from tests.datagen import generate_buffer


# =====================================================================
# compress_bound tests
# =====================================================================

class TestCompressBound:
    """Tests for compress_bound()."""

    def test_zero(self):
        assert compress_bound(0) == 16

    def test_small(self):
        assert compress_bound(1) == 17

    def test_typical(self):
        assert compress_bound(1000) == 1000 + 1000 // 255 + 16

    def test_large(self):
        result = compress_bound(1_000_000)
        assert result > 1_000_000

    def test_negative(self):
        assert compress_bound(-1) == 0

    def test_too_large(self):
        assert compress_bound(LZ4_MAX_INPUT_SIZE + 1) == 0

    def test_max_input(self):
        result = compress_bound(LZ4_MAX_INPUT_SIZE)
        assert result > LZ4_MAX_INPUT_SIZE


# =====================================================================
# Basic round-trip tests
# =====================================================================

class TestRoundTrip:
    """Test compress -> decompress round-trip with various data patterns."""

    def test_empty(self, empty_data):
        c = compress(empty_data)
        d = decompress(c, uncompressed_size=0)
        assert d == empty_data

    def test_small_text(self, small_text):
        c = compress(small_text)
        d = decompress(c, uncompressed_size=len(small_text))
        assert d == small_text

    def test_lorem_ipsum(self, lorem_ipsum):
        c = compress(lorem_ipsum)
        d = decompress(c, uncompressed_size=len(lorem_ipsum))
        assert d == lorem_ipsum
        # Verify compression actually happened
        assert len(c) < len(lorem_ipsum)

    def test_repetitive(self, repetitive_data):
        c = compress(repetitive_data)
        d = decompress(c, uncompressed_size=len(repetitive_data))
        assert d == repetitive_data
        # Very repetitive data should compress well
        assert len(c) < len(repetitive_data) // 10

    def test_all_zeros(self, all_zeros):
        c = compress(all_zeros)
        d = decompress(c, uncompressed_size=len(all_zeros))
        assert d == all_zeros

    def test_pattern(self, pattern_data):
        c = compress(pattern_data)
        d = decompress(c, uncompressed_size=len(pattern_data))
        assert d == pattern_data

    def test_random(self, random_data):
        c = compress(random_data)
        d = decompress(c, uncompressed_size=len(random_data))
        assert d == random_data

    def test_one_byte(self, one_byte):
        c = compress(one_byte)
        d = decompress(c, uncompressed_size=len(one_byte))
        assert d == one_byte

    def test_compressible(self, compressible_data):
        c = compress(compressible_data)
        d = decompress(c, uncompressed_size=len(compressible_data))
        assert d == compressible_data
        assert len(c) < len(compressible_data)

    def test_incompressible(self, incompressible_data):
        c = compress(incompressible_data)
        d = decompress(c, uncompressed_size=len(incompressible_data))
        assert d == incompressible_data

    def test_highly_compressible(self, highly_compressible_data):
        c = compress(highly_compressible_data)
        d = decompress(c, uncompressed_size=len(highly_compressible_data))
        assert d == highly_compressible_data
        # Should achieve good compression ratio
        assert len(c) < len(highly_compressible_data) // 2

    def test_various_sizes(self):
        """Test round-trip for various input sizes."""
        for size in [0, 1, 2, 3, 4, 5, 10, 12, 13, 14, 15, 16,
                     100, 255, 256, 1000, 4096, 10000, 65535, 65536, 100000]:
            data = generate_buffer(size, match_proba=0.5, seed=size)
            c = compress(data)
            d = decompress(c, uncompressed_size=size)
            assert d == data, f"Round-trip failed for size={size}"

    def test_bytearray_input(self):
        data = bytearray(b"test data for compression" * 50)
        c = compress(data)
        d = decompress(c, uncompressed_size=len(data))
        assert d == bytes(data)

    def test_memoryview_input(self):
        data = b"test data for compression" * 50
        mv = memoryview(data)
        c = compress(mv)
        d = decompress(c, uncompressed_size=len(data))
        assert d == data


# =====================================================================
# Acceleration parameter tests
# =====================================================================

class TestAcceleration:
    """Test compression with different acceleration values."""

    def test_acceleration_1(self, compressible_data):
        c = compress(compressible_data, acceleration=1)
        d = decompress(c, uncompressed_size=len(compressible_data))
        assert d == compressible_data

    def test_acceleration_high(self, compressible_data):
        c = compress(compressible_data, acceleration=10)
        d = decompress(c, uncompressed_size=len(compressible_data))
        assert d == compressible_data

    def test_higher_acceleration_less_compression(self, compressible_data):
        c1 = compress(compressible_data, acceleration=1)
        c10 = compress(compressible_data, acceleration=10)
        # Higher acceleration should produce equal or larger output
        assert len(c10) >= len(c1)


# =====================================================================
# compress_dest_size tests
# =====================================================================

class TestCompressDestSize:
    """Test compress_dest_size() for fixed-output-size compression."""

    def test_basic(self):
        data = generate_buffer(10000, match_proba=0.5, seed=42)
        target = 5000
        compressed, consumed = compress_dest_size(data, target)
        assert len(compressed) <= target
        assert consumed <= len(data)
        # The consumed portion should decompress correctly
        d = decompress(compressed, uncompressed_size=consumed)
        assert d == data[:consumed]

    def test_large_target(self):
        data = generate_buffer(1000, match_proba=0.5, seed=42)
        target = compress_bound(len(data))
        compressed, consumed = compress_dest_size(data, target)
        assert consumed == len(data)  # Everything should be consumed


# =====================================================================
# Partial decompression tests (ported from decompress-partial.c)
# =====================================================================

class TestPartialDecompression:
    """Test partial decompression, ported from decompress-partial.c."""

    def test_partial_basic(self):
        """Core test from decompress-partial.c."""
        source = (
            b"Lorem ipsum dolor sit amet, consectetur adipiscing elit, "
            b"sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. "
            b"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris "
            b"nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in "
            b"reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla "
            b"pariatur. Excepteur sint occaecat cupidatat non proident, sunt in "
            b"culpa qui officia deserunt mollit anim id est laborum. "
            b"Lorem ipsum dolor sit amet, consectetur adipiscing elit, "
            b"sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. "
        )
        src_len = len(source)

        # Compress
        compressed = compress(source)
        cmp_size = len(compressed)

        # Test partial decompression with varying srcSize (cmpSize .. cmpSize+9)
        buffer_size = 2 * src_len
        for i in range(cmp_size, cmp_size + 10):
            # Pad compressed data if needed
            padded = compressed + b'\x00' * max(0, i - cmp_size)
            result = decompress_partial(padded, i, src_len, buffer_size)
            assert len(result) >= src_len, (
                f"Partial decompression returned only {len(result)} bytes "
                f"for srcSize={i}, expected at least {src_len}"
            )
            assert result[:src_len] == source

    def test_partial_various_targets(self):
        """Test partial decompression with various target sizes."""
        data = generate_buffer(10000, match_proba=0.5, seed=42)
        compressed = compress(data)
        cmp_size = len(compressed)

        for target in [1, 10, 100, 1000, 5000, len(data)]:
            result = decompress_partial(
                compressed, cmp_size, target, target
            )
            assert len(result) <= target
            assert result == data[:len(result)]


# =====================================================================
# Dictionary decompression tests (ported from decompress-partial-usingDict.c)
# =====================================================================

class TestDictionaryDecompression:
    """Test dictionary-based decompression."""

    def test_no_dict(self):
        """Scenario 1: No dictionary (dict=NULL, dictSize=0)."""
        source = (
            b"Lorem ipsum dolor sit amet, consectetur adipiscing elit, "
            b"sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. "
            b"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris "
            b"nisi ut aliquip ex ea commodo consequat. "
        )
        compressed = compress(source)
        cmp_size = len(compressed)

        for i in range(cmp_size, cmp_size + 10):
            padded = compressed + b'\x00' * max(0, i - cmp_size)
            result = decompress_partial_using_dict(
                padded, i, len(source), 2 * len(source),
                None, 0,
            )
            assert len(result) >= len(source)
            assert result[:len(source)] == source

    def test_with_external_dict(self):
        """Test decompression with external dictionary data."""
        # Create dict-compressed data: use the streaming encoder
        enc = LZ4StreamEncode()
        dict_data = generate_buffer(4096, match_proba=0.5, seed=100)
        enc.load_dict(dict_data)

        source = generate_buffer(4096, match_proba=0.5, seed=200)
        compressed = enc.compress_continue(source, max_output_size=compress_bound(len(source)))

        # Decompress using the dictionary
        result = decompress_using_dict(
            compressed, len(compressed), len(source),
            dict_data, len(dict_data),
        )
        assert result == source


# =====================================================================
# Streaming encode/decode tests
# =====================================================================

class TestStreaming:
    """Test LZ4StreamEncode and LZ4StreamDecode."""

    def test_basic_stream_roundtrip(self):
        """Compress and decompress independent blocks via streaming API."""
        enc = LZ4StreamEncode()

        blocks = [
            generate_buffer(1000, match_proba=0.5, seed=i)
            for i in range(5)
        ]

        # Each block compressed independently (no cross-block references)
        for i, block in enumerate(blocks):
            enc.reset()
            c = enc.compress_continue(block)
            d = decompress(c, uncompressed_size=len(block))
            assert d == block, f"Stream block {i} mismatch"

    def test_load_dict(self):
        """Test loading a dictionary and compressing."""
        enc = LZ4StreamEncode()
        dict_data = generate_buffer(32768, match_proba=0.5, seed=42)
        loaded = enc.load_dict(dict_data)
        assert loaded == len(dict_data)

        data = generate_buffer(4096, match_proba=0.5, seed=100)
        compressed = enc.compress_continue(data)
        assert len(compressed) > 0

    def test_save_dict(self):
        """Test saving dictionary after compression."""
        enc = LZ4StreamEncode()
        data = generate_buffer(10000, match_proba=0.5, seed=42)
        enc.compress_continue(data)

        saved = enc.save_dict(4096)
        assert len(saved) <= 4096
        assert len(saved) > 0

    def test_stream_reset(self):
        """Test reset clears state properly."""
        enc = LZ4StreamEncode()
        data = generate_buffer(1000, match_proba=0.5, seed=42)
        enc.compress_continue(data)

        enc.reset()
        # Should be able to compress again from scratch
        c = enc.compress_continue(data)
        assert len(c) > 0


# =====================================================================
# Error handling tests
# =====================================================================

class TestErrorHandling:
    """Test error handling for invalid inputs."""

    def test_decompress_truncated(self):
        """Truncated compressed data should raise an error."""
        data = generate_buffer(1000, match_proba=0.5, seed=42)
        compressed = compress(data)
        # Truncate the compressed data
        truncated = compressed[:len(compressed) // 2]
        with pytest.raises(LZ4DecompressError):
            decompress(truncated, uncompressed_size=len(data))

    def test_decompress_corrupted(self):
        """Corrupted compressed data should raise or return wrong result.

        Note: LZ4 block format corruption may not always be detected;
        the decompressor is allowed to produce wrong output. We test that
        at minimum, the output differs from the original.
        """
        data = generate_buffer(1000, match_proba=0.5, seed=42)
        compressed = bytearray(compress(data))
        # Corrupt the middle of the compressed data
        if len(compressed) > 10:
            compressed[len(compressed) // 2] ^= 0xFF
        try:
            result = decompress(bytes(compressed), uncompressed_size=len(data))
            # If no error was raised, the result should differ from original
            assert result != data, "Corrupted data decompressed to original"
        except LZ4DecompressError:
            pass  # Expected

    def test_decompress_wrong_size(self):
        """Wrong uncompressed_size should raise an error."""
        data = b"test data" * 100
        compressed = compress(data)
        with pytest.raises(LZ4DecompressError):
            decompress(compressed, uncompressed_size=len(data) // 2)

    def test_compress_negative_max_output(self):
        """Negative max_output_size should raise."""
        with pytest.raises(LZ4CompressError):
            compress(b"x", max_output_size=-1)

    def test_decompress_empty_input(self):
        """Empty input should raise."""
        with pytest.raises(LZ4DecompressError):
            decompress(b"", uncompressed_size=100)

    def test_decompress_zero_offset(self):
        """A block with a zero offset should be detected as corrupted."""
        # Craft a malicious block: token=0x10 (1 literal, 0 match len) + literal + offset=0
        malicious = bytes([0x10, 0x41, 0x00, 0x00])  # token, literal 'A', offset=0
        with pytest.raises(LZ4DecompressError):
            decompress(malicious, uncompressed_size=100)


# =====================================================================
# Datagen integration tests
# =====================================================================

class TestDatagenIntegration:
    """Test round-trip with datagen-generated data at different compressibility levels."""

    @pytest.mark.parametrize("match_proba", [0.0, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95])
    def test_compressibility_levels(self, match_proba):
        """Round-trip with various compressibility levels."""
        data = generate_buffer(50_000, match_proba=match_proba, seed=42)
        compressed = compress(data)
        decompressed = decompress(compressed, uncompressed_size=len(data))
        assert decompressed == data

    @pytest.mark.parametrize("size", [0, 1, 12, 13, 100, 1000, 10000, 100000])
    def test_various_sizes_datagen(self, size):
        """Round-trip with various data sizes."""
        data = generate_buffer(size, match_proba=0.5, seed=42)
        compressed = compress(data)
        if size == 0:
            decompressed = decompress(compressed, uncompressed_size=0)
        else:
            decompressed = decompress(compressed, uncompressed_size=len(data))
        assert decompressed == data

    @pytest.mark.parametrize("seed", range(10))
    def test_different_seeds(self, seed):
        """Round-trip with different random seeds."""
        data = generate_buffer(10_000, match_proba=0.5, seed=seed)
        compressed = compress(data)
        decompressed = decompress(compressed, uncompressed_size=len(data))
        assert decompressed == data


# =====================================================================
# Golden samples tests
# =====================================================================

class TestGoldenSamples:
    """Test with golden sample files from the C test suite."""

    def test_skip_bin_exists(self):
        """Verify skip.bin golden sample is present."""
        golden_dir = os.path.join(os.path.dirname(__file__), "golden_samples")
        skip_path = os.path.join(golden_dir, "skip.bin")
        assert os.path.exists(skip_path), f"Golden sample not found: {skip_path}"
        with open(skip_path, "rb") as f:
            data = f.read()
        assert len(data) == 38, f"skip.bin should be 38 bytes, got {len(data)}"

    def test_skip_bin_magic(self):
        """Verify skip.bin starts with the expected magic bytes."""
        golden_dir = os.path.join(os.path.dirname(__file__), "golden_samples")
        skip_path = os.path.join(golden_dir, "skip.bin")
        with open(skip_path, "rb") as f:
            data = f.read()
        # skip.bin is an LZ4 frame with a skippable frame marker
        # The magic bytes should be present
        assert len(data) >= 4


# =====================================================================
# Auto-detect decompression size
# =====================================================================

class TestAutoDetectSize:
    """Test decompression without knowing the output size."""

    def test_auto_detect_small(self):
        data = b"Hello World! " * 10
        compressed = compress(data)
        # decompress without specifying size (uses heuristic)
        decompressed = decompress(compressed)
        assert decompressed == data

    def test_auto_detect_medium(self):
        data = generate_buffer(10_000, match_proba=0.5, seed=42)
        compressed = compress(data)
        decompressed = decompress(compressed)
        assert decompressed == data

    def test_auto_detect_repetitive(self):
        data = b"x" * 10000
        compressed = compress(data)
        decompressed = decompress(compressed)
        assert decompressed == data
